name: Daily Commit

on:
  schedule:
    - cron: "0 6 * * *" # هر روز ساعت 6 صبح UTC
  # workflow_dispatch: حذف شد، فقط خودکار

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Make a change
        run: |
          echo "$(date) - commit by GitHub Actions" >> log.txt

      - name: Commit changes
        run: |
          git config user.name "ahmadrz1379"
          git config user.email "aahmadrezarezaee@gmail.com"
          git add .
          git commit -m "daily commit - $(date)" || echo "nothing to commit"
          git push origin main
